### ISSUE TITLE
Add support for password less authentication

### ISSUE THREAD

**Issue by gyfchong** [mitchelvanbever/remix-auth-supabase#12]
Hello,

I tried to change the `signInWithEmail` to use Supabase `signIn` but it didn't seem to work. I was wondering if it were possible to get an example or support for passwordless auth.

Thanks

**Comment by rphlmr** [comment]
Hello @gyfchong 

Challenge accepted 😉

You can check this pull request : https://github.com/mitchelvanbever/remix-auth-supabase/pull/13 

You can trick this base to fit your needs.

I hope you get the idea 😇

___
If someone wants to know why everything cannot be done server side, [check this](https://github.com/supabase/supabase/issues/1698#issuecomment-847646400)

**Comment by rphlmr** [comment]
You can find a passwordless example here : https://github.com/mitchelvanbever/remix-auth-supabase/tree/main/examples/magic-link
Tell us if it works for you 😎

**Comment by gyfchong** [comment]
Thanks @rphlmr it worked perfectly!
