### ISSUE TITLE
Get stuck on oauth.callback.ts after succesfully login with github provider example

### ISSUE THREAD

**Issue by mirkoisaia** [mitchelvanbever/remix-auth-supabase#33]
### Describe the bug

I tried both making my own and downloading the folder in example/oauth,
both cases, google or github doesn't matter, the cycle get stuck on it get to oatuh, the supabase.auth.onAuthStateChange triggers, and it seems something get lost between submit() and action

unable to understand what, unfortunely. 
but downloading the example and running it reproduce my problem

### Your Example Website or App

https://github.com/remix-run/remix/tree/main/examples/remix-auth-supabase-github

### Steps to Reproduce the Bug or Issue

Download,
install,
run dev,
try to login,
get stuck on page oauth.callback.ts

### Expected behavior

useSubmit() should trigger and complete the login cycle? just redirect?

### Platform

- OS: Windows 10
- Browser: Latest Firefox

**Comment by mirkoisaia** [comment]
And that indeed solve the problems. Got redirected to private, and the session get set, being able to recall user id :)

**Comment by rphlmr** [comment]
Thanks for the feedback, I'll try to find some time to update example here and on remix 🥳
