### ISSUE TITLE
Calling `request.formData()` stops authenticator completion

### ISSUE THREAD

**Issue by chenkie** [mitchelvanbever/remix-auth-supabase#44]
### Describe the bug

Hello! 

I'm not certain if this would be a bug/limitation in this package or if it might relate to remix-auth or remix more broadly. Here's what I'm trying to do:

I'm using the `sb-magic-link` strategy and all works well. My callback page has an `ActionFunction` that looks like this:

```ts
export const action: ActionFunction = async ({ request }: ActionArgs) => {
  await authenticator.authenticate("sb-magic-link", request, {
    successRedirect: '/my-redirect',
    failureRedirect: '/other-redirect',
  });
};
```

However, I now want to add a call to another function before completing the `authenticate` step. The call to the other function relies on session info from the `request`.

If I try to access the `session` via `formData`, I'm able to, but the authentication doesn't complete.

```ts
export const action: ActionFunction = async ({ request }: ActionArgs) => {
  const formData = await request.formData();  // nothing happens after this

  await authenticator.authenticate("sb-magic-link", request, {
    successRedirect: '/my-redirect',
    failureRedirect: '/other-redirect',
  });
};
```

Any tips on how I might troubleshoot?

Thanks!

### Your Example Website or App

local

### Steps to Reproduce the Bug or Issue

1. Use `sb-magic-link` as a strategy
2. In the `ActionFunction`, call `await request.formData()` before executing `authenticate`
3. Authentication does not complete

### Expected behavior

Be able to use the `request` object to get `formData` and then proceed with authentication.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 107.0.5304

**Comment by rphlmr** [comment]
Hello @chenkie,

You have to [clone](https://developer.mozilla.org/en-US/docs/Web/API/Request/clone) your `request` before getting its `formData`:

`const formData = await request.clone().formData()`

The reason is that Remix Auth tries to read the formData and you can do that once per request (it's a stream) 😇.

Depending Remix Auth version you use, [you can rid of the cloning process and pass a context]( https://github.com/sergiodxa/remix-auth-form#passing-a-pre-read-formdata-object) to `authenticator.authenticate`

**Comment by chenkie** [comment]
ahhh thanks! I had a hunch that it might be an issue with needing to copy `request` and I tried with just simple object copy but didn't work. I wasn't aware of `clone()`.

Trying now!

**Comment by chenkie** [comment]
Confirmed it works, many thanks!

**Comment by rphlmr** [comment]
You are welcome ;)
