### ISSUE TITLE
Rename package to `remix-auth-supabase`?

### ISSUE THREAD

**Issue by MichaelDeBoey** [mitchelvanbever/remix-auth-supabase#7]
To be consistent with other strategy packages

Official packages:
- https://github.com/sergiodxa/remix-auth-form
- https://github.com/sergiodxa/remix-auth-github
- https://github.com/sergiodxa/remix-auth-github
- https://github.com/sergiodxa/remix-auth-token

Community packages:
- https://github.com/danestves/remix-auth-auth0
- https://github.com/pbteja1998/remix-auth-email-link
- https://github.com/pbteja1998/remix-auth-google
- https://github.com/juhanakristian/remix-auth-microsoft
- https://github.com/Andreychik32/remix-auth-steam

Also publish it as `remix-auth-supabase`?

**Comment by rphlmr** [comment]
Seems a good idea, what do you think @MichaelDeBoey ?

I'm following this, in case of, to update all demo published :D

**Comment by mitchelvanbever** [comment]
I think the request makes sense! Consistency goes a long way for ease-of-usage.

I'll see what I can do later today 🚀

**Comment by MichaelDeBoey** [comment]
Once it's consistent, it will also be easier to discover imo.

People can just *guess* the package name of the supabase strategy that way

**Comment by mitchelvanbever** [comment]
Let's hope [this](https://www.npmjs.com/package/@afaik/remix-auth-supabase-strategy) will help people to find the right package as NPM's renaming / deprecation / unpublishing policy is little rougher than renaming the repo on github 😁 

But you'll notice I've updated the github repo, package.json and current examples (sorry @rphlmr 😬 ) and you can find the new published 3.0.1 version [here](https://www.npmjs.com/package/remix-auth-supabase)

I'll check to see if there are any other places where it needs updating but I think we caught it early. Thanks @MichaelDeBoey 👍

**Comment by rphlmr** [comment]
don't worry @MichaelDeBoey  all example are already updated :D
